### ISSUE TITLE
Set "from" name in emails

### ISSUE THREAD

**Issue by Kaweechelchen** [opendatalu/udata2#3]
emails sent by the portal only mention info@data.public.lu
maybe set it to "Portail Open Data" like the title tag of the website says

**Comment by grischard** [comment]
Ready for Ansible

https://trello.com/c/WkakOuJo/70-set-from-name-in-emails

**Comment by grischard** [comment]
Email From is now: Plateforme des données ouvertes publiques luxembourgeoises info@data.public.lu

Thanks!
