### ISSUE TITLE
time stamps are not updated (last modified) when updating a ressource by API

### ISSUE THREAD

**Issue by jaykayone** [opendatalu/udata2#5]
https://data.public.lu/en/datasets/adresses-georeferencees-bd-adresses/
The ressources have been updated by API (cf the timestamp in the URL to the ressources), but the timestamps on the page are still on the old date

**Comment by grischard** [comment]
I can't reproduce this - the date updates fine for me. Can you please provide the steps you use? Can you still reproduce this on dev?

**Comment by grischard** [comment]
Don't forget to set the publication date when updating a resource :)
